services:
  backend:
    image: danilosantana1/finances-backend-av3:latest
    container_name: backend-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/finances
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      
      # Variáveis extras que seu app pode precisar
      SECRET_KEY: chave_secreta_teste_123
      
      # Com essa config, o Hibernate cria/atualiza as tabelas automaticamente
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - minha-rede

  database:
    image: postgres:16.3
    container_name: database-container
    restart: always
    environment:
      # Configurações do container do Postgres
      POSTGRES_DB: finances
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - minha-rede

volumes:
  pgdata:

networks:
  minha-rede:
    driver: bridge